declare module 'react-reveal/Slide'
declare module 'react-reveal/Zoom'
declare module 'naija-state-local-government'
declare module 'react-dropzone'
declare module 'draft-js'
declare module 'draftjs-to-html'
declare module "html-to-react"
declare module "jodit-react"
declare module  "quill-better-table"
